version: '3'

services:

  webApp:
    image: uo257431/prog_query_web_app:latest
    container_name: webApp
    restart: always
    depends_on:
      - sql
      - neo4j
    ports:
      - "80:8080"
    entrypoint: sh -c './wait-for sql:3306 -- java -Djava.security.egd=file:/dev/./urandom -jar app.jar'

  neo4j:
    image: neo4j:4.0
    container_name: neo4jDB
    restart: always
    environment:
      NEO4J_AUTH: neo4j/s3cr3t0.
      NEO4J_dbms_memory_heap_maxSize: 2G
      NEO4J_dbms.connector.http.listen_address: 0.0.0.0:7474
    expose:
      - 7687

  sql:
    image: mysql/mysql-server:8.0
    container_name: sqlDB
    restart: always
    environment:
      MYSQL_DATABASE: db
      MYSQL_ROOT_PASSWORD: dbp4ssw0rd
      MYSQL_ROOT_HOST: '%'
    expose:
      - 3306
