version: '3'

services:

  webApp:
    image: uo257431/prog_query_web_app:latest
    container_name: webApp
    restart: always
    depends_on:
      - sql
      - neo4j
    ports:
      - 8080:80

  neo4j:
    image: neo4j:3.5
    container_name: neo4jDB
    restart: always
    environment:
      NEO4J_AUTH: neo4j/s3cr3t0.
    expose:
      - 7687

  sql:
    image: blacklabelops/hsqldb
    container_name: sqlDB
    restart: always
    enviroment:
      HSQLDB_USER: SA
      HSQLDB_PASSWORD: dbp4ssw0rd
      HSQLDB_DATABASE_HOST: '%'
    expose:
      - 9001
